name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening an issue. Please keep in mind that we are busy and getting back to you can take some time'
        pr-message: 'Thanks for your pull-request, please be patient as we review'
